### PR TITLE
The libvirt group on Ubuntu 16.04 is libvirt

### PR DESCRIPTION
**Pull request by roedie**

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@roedie Good catch. To maintain backward compatibility with older versions we should should add the logic to the template based on Ubuntu version and/or other distro.
For example something similar to:
```
{% if ansible_distribution == "Ubuntu" and ansible_distribution_version >= '16.04' %}
unix_sock_group = "libvirt"
{% elif %}
unix_sock_group = "libvirtd"
{% endif %}
```

**Comment by mrlesmithjr** [comment]
@roedie Merged.

**Comment by mrlesmithjr** [comment]
@roedie I just pushed this out to a few of my KVM hosts on `Ubuntu 16.04` and this change broke my hosts because they are setup to use the group `libvirtd`. Not sure why mine is different then your's but may need to do some additional testing to figure out what the differences are.

**Comment by mrlesmithjr** [comment]
According to [Ubuntu Libvirt Guide](https://help.ubuntu.com/lts/serverguide/libvirt.html) the below is what is said. So this does not apply to Xenial.

```
In more recent releases (>= Yakkety) the group was renamed to libvirt. Upgraded systems get a new libvirt group with the same gid as the libvirtd group to match that.
```

**Comment by roedie** [comment]
I will have a look. I'm using 3 freshly installed `Ubuntu 16.04` hosts, but I do not have the `libvirtd` group.

Let me get back on this.

**Comment by roedie** [comment]
And just after I post my previous message it occurs to me that I am using the official `Ubuntu Cloud Archive`.

Just tested this and indeed, that is the difference. If you use libvirt from the standard `Ubuntu Xenial` repository you get the `libvirtd` group. When you use the `Ubuntu Cloud Archive` you get the `libvirt` group.

Not sure what a correct solution would be to fix this. We could use libvirtd group when <= 16.04 or if overruled by user.

**Comment by mrlesmithjr** [comment]
So that is interesting. I just spun up a Vagrant [Ubuntu Xenial 16.04 Cloud Image](http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box), installed KVM and it created the `libvirtd` group.
```
ubuntu@node0:/etc/libvirt$ getent group libvirt
ubuntu@node0:/etc/libvirt$ getent group libvirtd
libvirtd:x:119:ubuntu
ubuntu@node0:/etc/libvirt$
```

**Comment by mrlesmithjr** [comment]
And after spinning up a Vagrant [Ubuntu Yakkety 16.10 Cloud Image](http://cloud-images.ubuntu.com/yakkety/current/yakkety-server-cloudimg-amd64-vagrant.box), it creates the `libvirt` group.
```
ubuntu@node0:~$ getent group libvirt
libvirt:x:119:ubuntu
ubuntu@node0:~$ getent group libvirtd
ubuntu@node0:~$
```

**Comment by roedie** [comment]
Ah, no, that's not what I meant. I am using the `Cloud Archive Repository` located at  `deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main`.

So, I install a clean `Ubuntu 16.04 LTS Server`, after that I add the above repository with ansible and apply the KVM role.

**Comment by mrlesmithjr** [comment]
gotcha

**Comment by mrlesmithjr** [comment]
I think I have something that will work to keep the work from the end-user. Will be committing here in a few. Can you test it on your side once I commit?

**Comment by roedie** [comment]
Yes, sure.

**Comment by mrlesmithjr** [comment]
Ok it is all set to go in `master`

**Comment by mrlesmithjr** [comment]
This new method works on my side from the different installs.

**Comment by roedie** [comment]
Just deployed my dev setup, everything seems to work fine.

**Comment by mrlesmithjr** [comment]
awesome!

**Pull request merged**
